'use client';

import { useState, useCallback, useEffect } from 'react';
import type { ExportButtonProps } from '../types.js';

interface ManifestEntry {
  filename: string;
  path: string;
}

type Manifest = Record<string, ManifestEntry>;

// Cache manifest fetches across component instances
let manifestCache: Record<string, { data: Manifest | null; promise?: Promise<Manifest | null> }> = {};

function fetchManifest(manifestPath: string): Promise<Manifest | null> {
  if (manifestCache[manifestPath]?.data !== undefined && manifestCache[manifestPath]?.promise === undefined) {
    return Promise.resolve(manifestCache[manifestPath].data);
  }
  if (manifestCache[manifestPath]?.promise) {
    return manifestCache[manifestPath].promise!;
  }

  const promise = fetch(manifestPath)
    .then((res) => {
      if (!res.ok) return null;
      return res.json() as Promise<Manifest>;
    })
    .then((data) => {
      manifestCache[manifestPath] = { data };
      return data;
    })
    .catch(() => {
      manifestCache[manifestPath] = { data: null };
      return null;
    });

  manifestCache[manifestPath] = { data: null as unknown as Manifest, promise };
  return promise;
}

/**
 * Button component that triggers PDF export of the current page.
 *
 * Supports two modes:
 * - **Manifest mode**: Serves pre-rendered static PDFs generated by the CLI
 * - **Live mode**: Generates PDFs on-demand via server API (requires Puppeteer)
 *
 * When both `manifestPath` and `apiPath` are set, manifest is checked first
 * with live generation as fallback.
 *
 * @example
 * // Static only (pre-rendered PDFs)
 * <ExportButton manifestPath="/pdfs/manifest.json" apiPath={null} />
 *
 * @example
 * // Live only (existing behavior)
 * <ExportButton apiPath="/api/export-pdf" />
 *
 * @example
 * // Manifest with live fallback
 * <ExportButton manifestPath="/pdfs/manifest.json" apiPath="/api/export-pdf" />
 */
export function ExportButton({
  apiPath = '/api/export-pdf',
  manifestPath,
  className,
  children,
  title = 'Export as PDF',
  onExportStart,
  onExportSuccess,
  onExportError,
  filename,
  disabled,
  hideWhenUnavailable = false,
}: ExportButtonProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [manifestEntry, setManifestEntry] = useState<ManifestEntry | null | undefined>(
    // undefined = not checked yet, null = checked but not found
    manifestPath ? undefined : null
  );

  // Check manifest for current page on mount
  useEffect(() => {
    if (!manifestPath) {
      setManifestEntry(null);
      return;
    }

    const currentPath = window.location.pathname;
    fetchManifest(manifestPath).then((manifest) => {
      if (manifest && manifest[currentPath]) {
        setManifestEntry(manifest[currentPath]);
      } else {
        setManifestEntry(null);
      }
    });
  }, [manifestPath]);

  const handleExport = useCallback(async () => {
    if (isLoading || disabled) return;

    setIsLoading(true);
    onExportStart?.();

    try {
      const currentPath = window.location.pathname;

      // Try manifest (static PDF) first
      if (manifestEntry && manifestPath) {
        const pdfDir = manifestPath.replace(/\/[^/]+$/, '');
        const pdfUrl = `${pdfDir}/${manifestEntry.filename}`;
        const a = document.createElement('a');
        a.href = pdfUrl;
        a.download = filename ? `${filename}.pdf` : manifestEntry.filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        onExportSuccess?.();
        return;
      }

      // Fall back to live API generation
      if (!apiPath) {
        throw new Error('No PDF available for this page');
      }

      const response = await fetch(`${apiPath}?path=${encodeURIComponent(currentPath)}`);

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.details || 'Failed to generate PDF');
      }

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename
        ? `${filename}.pdf`
        : `${currentPath.replace(/\//g, '-').replace(/^-/, '') || 'document'}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);

      onExportSuccess?.();
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error));
      console.error('[PDF Export] Error:', err);
      onExportError?.(err);
    } finally {
      setIsLoading(false);
    }
  }, [apiPath, manifestPath, manifestEntry, filename, isLoading, disabled, onExportStart, onExportSuccess, onExportError]);

  // Hide button if manifest-only mode and no PDF available
  if (hideWhenUnavailable && !apiPath && manifestEntry === null && manifestPath) {
    return null;
  }

  // Still loading manifest, hide if we might need to hide
  if (manifestEntry === undefined && hideWhenUnavailable && !apiPath) {
    return null;
  }

  const isDisabled = isLoading || disabled || (manifestEntry === undefined && !apiPath);

  return (
    <button
      onClick={handleExport}
      disabled={isDisabled}
      className={className}
      title={title}
      aria-busy={isLoading}
    >
      {children ?? (isLoading ? 'Generating...' : 'Export PDF')}
    </button>
  );
}

/**
 * Pre-styled ExportButton for Fumadocs projects
 * Uses Fumadocs CSS variables for consistent styling
 */
export function FumadocsExportButton(props: Omit<ExportButtonProps, 'className' | 'children'>) {
  const [isLoading, setIsLoading] = useState(false);

  return (
    <ExportButton
      {...props}
      onExportStart={() => {
        setIsLoading(true);
        props.onExportStart?.();
      }}
      onExportSuccess={() => {
        setIsLoading(false);
        props.onExportSuccess?.();
      }}
      onExportError={(err) => {
        setIsLoading(false);
        props.onExportError?.(err);
      }}
      className="inline-flex items-center gap-2 rounded-md border border-fd-border bg-fd-background px-3 py-1.5 text-sm text-fd-muted-foreground hover:bg-fd-accent hover:text-fd-accent-foreground transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
    >
      {isLoading ? (
        <>
          <LoadingSpinner />
          Generating...
        </>
      ) : (
        <>
          <PrinterIcon />
          Export PDF
        </>
      )}
    </ExportButton>
  );
}

function PrinterIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="6 9 6 2 18 2 18 9" />
      <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
      <rect width="12" height="8" x="6" y="14" />
    </svg>
  );
}

function LoadingSpinner() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="animate-spin"
      style={{ animation: 'spin 1s linear infinite' }}
    >
      <path d="M21 12a9 9 0 1 1-6.219-8.56" />
    </svg>
  );
}
